version: '3.8'

services:
  myapi-dev:
    build: .
    container_name: myapi-dev
    ports:
      - "4500:4500"
    environment:
      - PORT=4500
      - NODE_ENV=development
    env_file:
      - src/.env
    volumes:
      - ./src/db.sqlite:/app/src/db.sqlite
      - ./src/logs:/app/src/logs
    restart: unless-stopped

